import type { Metadata, Viewport } from "next";
import {HeroUIProvider} from "@heroui/react";
import { Inter } from "next/font/google";
import { Footer } from "@/components/main/footer";
import { Navbar } from "@/components/main/navbar";
import { StarsCanvas } from "@/components/main/star-background";
import { cn } from "@/lib/utils";
import { SmoothCursor } from "@/components/ui/smooth-cursor";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#030014",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-[#030014] overflow-y-scroll overflow-x-hidden",
          inter.className
        )}
      >
        {/* <video autoPlay muted loop playsInline>
          <source src="video.webm" type="video/webm" />
        </video> */}
          <SmoothCursor />
          <StarsCanvas />
        <HeroUIProvider>
          <Navbar />
        </HeroUIProvider>
        {children}
        <Footer />
      </body>
    </html>
  );
}
